with seed_listings (
  title,
  category,
  subcategory,
  description,
  location,
  distance_miles,
  price_per_day,
  deposit_amount,
  replacement_value,
  rating,
  review_count,
  owner_name,
  owner_type,
  availability_status,
  condition,
  image_url,
  features,
  safety_notes,
  pickup_instructions
) as (
  values
    (
      'Specialized Tarmac Carbon Road Bike',
      'Bikes',
      'Road bikes',
      'Lightweight carbon road bike with Shimano 105, fresh brake pads, and a professional shop tune before each rental.',
      'Boulder, CO',
      1.4,
      64,
      250,
      4200,
      4.9,
      186,
      'Boulder Cycle Works',
      'shop',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80',
      array['Carbon frame', 'Shimano 105', 'Flat kit included', 'Shop tuned'],
      'Helmet strongly recommended. Shop will confirm sizing and fit before pickup.',
      'Pick up at the Pearl Street shop desk with photo ID.'
    ),
    (
      'Cannondale Topstone Gravel Bike',
      'Bikes',
      'Gravel bikes',
      'Stable aluminum gravel bike with 40mm tires, tubeless setup, and mounts for bags.',
      'Fort Collins, CO',
      3.8,
      58,
      200,
      2600,
      4.8,
      94,
      'Front Range Adventure Co.',
      'shop',
      'limited',
      'excellent',
      'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80',
      array['40mm gravel tires', 'Tubeless setup', 'Bottle cages', 'Repair kit'],
      'Rental includes a quick fit check and route guidance for current trail conditions.',
      'Meet at the rental counter after confirmation.'
    ),
    (
      'Santa Cruz Hightower Full-Suspension Mountain Bike',
      'Bikes',
      'Mountain bikes',
      'Trail-ready full-suspension mountain bike with dropper post and fresh sealant.',
      'Moab, UT',
      2.1,
      88,
      350,
      5400,
      4.9,
      223,
      'Redrock Bike & Trail',
      'shop',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1593764592116-bfb2a97c642a?auto=format&fit=crop&w=1200&q=80',
      array['150mm travel', 'Dropper post', 'Tubeless tires', 'Trail map included'],
      'Riders should be comfortable on intermediate trails. Body armor is available at pickup.',
      'Pick up at the shop garage entrance for suspension setup.'
    ),
    (
      'Trek Allant+ Commuter E-Bike',
      'Bikes',
      'E-bikes',
      'Comfortable pedal-assist e-bike with integrated lights, rear rack, and long-range battery.',
      'Bend, OR',
      4.2,
      72,
      300,
      3600,
      4.7,
      71,
      'Cascade Electric Rides',
      'shop',
      'limited',
      'good',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1200&q=80',
      array['Pedal assist', 'Integrated lights', 'Rear rack', 'Lock included'],
      'Class 1 pedal assist. Riders receive a controls walkthrough before pickup.',
      'Pick up from the downtown Bend storefront.'
    ),
    (
      'Burton Snowboard Package',
      'Snow Sports',
      'Snowboards',
      'All-mountain snowboard package with board, bindings, and boots.',
      'Park City, UT',
      0.9,
      52,
      175,
      1100,
      4.8,
      158,
      'Summit Snow Rentals',
      'shop',
      'available',
      'good',
      'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
      array['Board', 'Bindings', 'Boots', 'Stance adjustment'],
      'Binding setup is checked by shop staff. Helmets can be added at pickup.',
      'Pickup is two blocks from the town lift.'
    ),
    (
      'Rossignol Performance Ski Package',
      'Snow Sports',
      'Skis',
      'Performance ski package with skis, boots, poles, and DIN setup by certified technicians.',
      'Breckenridge, CO',
      1.1,
      61,
      200,
      1400,
      4.9,
      204,
      'Alpine Basecamp Rentals',
      'shop',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1605540436563-5bca919ae766?auto=format&fit=crop&w=1200&q=80',
      array['Skis', 'Boots', 'Poles', 'DIN setup'],
      'DIN settings require height, weight, age, boot sole length, and skier type at pickup.',
      'Check in at the Main Street tuning desk.'
    ),
    (
      'Loaded Tan Tien Longboard',
      'Boards',
      'Longboards',
      'Flexible carving longboard with smooth wheels for cruising coast paths or campus routes.',
      'Santa Cruz, CA',
      2.6,
      18,
      60,
      320,
      4.7,
      27,
      'Maya R.',
      'individual',
      'available',
      'good',
      'https://images.unsplash.com/photo-1547447134-cd3f5c716030?auto=format&fit=crop&w=1200&q=80',
      array['Carving deck', 'Soft wheels', 'Helmet available', 'Beginner friendly'],
      'Avoid steep descents and wet pavement. Helmet available on request.',
      'Pickup near Westside Santa Cruz after confirmation.'
    ),
    (
      'Inflatable Paddleboard Kit',
      'Water Sports',
      'Paddleboards',
      'Stable inflatable paddleboard with paddle, pump, leash, and personal flotation device.',
      'Austin, TX',
      1.7,
      39,
      125,
      780,
      4.8,
      132,
      'Lady Bird Paddle Co.',
      'shop',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      array['Inflatable board', 'Paddle', 'Pump', 'PFD included'],
      'PFD is included and expected on the water. Do not use during lightning advisories.',
      'Pick up dockside at the Lady Bird Paddle kiosk.'
    ),
    (
      'Perception Sit-On-Top Kayak',
      'Water Sports',
      'Kayaks',
      'Stable recreational kayak for mellow river floats and lake paddles.',
      'Asheville, NC',
      5.3,
      44,
      150,
      950,
      4.7,
      88,
      'Blue Ridge River Outfitters',
      'shop',
      'limited',
      'good',
      'https://images.unsplash.com/photo-1472740378865-80aab8e73251?auto=format&fit=crop&w=1200&q=80',
      array['Paddle', 'PFD', 'Dry bag', 'Launch guidance'],
      'Designed for flatwater and mellow flows. Rentals pause during unsafe river levels.',
      'Pick up from the river outpost.'
    ),
    (
      'Big Agnes Copper Spur 2-Person Tent',
      'Camping Gear',
      'Camping tents',
      'Lightweight two-person backpacking tent with footprint, stakes, and repair sleeve.',
      'Denver, CO',
      6.4,
      24,
      100,
      550,
      4.6,
      34,
      'Cam D.',
      'individual',
      'available',
      'good',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80',
      array['Sleeps two', 'Footprint', 'Stakes', 'Repair sleeve'],
      'Return dry when possible. If weather prevents drying, note it in the return message.',
      'Pickup in the Highlands neighborhood after confirmation.'
    ),
    (
      'Thule T2 Pro XTR Hitch Bike Rack',
      'Accessories',
      'Bike racks',
      'Two-bike hitch rack that fits 2-inch receivers and carries mountain, gravel, road, and many e-bikes.',
      'Boulder, CO',
      2.9,
      22,
      120,
      800,
      4.8,
      41,
      'Jordan P.',
      'individual',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1529422643029-d4585747aaf2?auto=format&fit=crop&w=1200&q=80',
      array['2-inch hitch', 'Carries two bikes', 'Lock cores', 'Owner walkthrough'],
      'Renter is responsible for confirming hitch compatibility before pickup.',
      'Pickup near North Boulder with owner-assisted mounting.'
    ),
    (
      'Trail Helmet and Accessory Bundle',
      'Accessories',
      'Helmets and accessory bundles',
      'Add-on bundle with trail helmet, lock, flat kit, lights, and compact pump.',
      'Boulder, CO',
      1.2,
      15,
      50,
      260,
      4.8,
      112,
      'Trailhead Gear Library',
      'shop',
      'available',
      'excellent',
      'https://images.unsplash.com/photo-1593764592116-bfb2a97c642a?auto=format&fit=crop&w=1200&q=80',
      array['Helmet', 'Lock', 'Flat kit', 'Lights and pump'],
      'Helmet fit is checked at pickup. Replace after any crash or hard impact.',
      'Bundle is prepared at the shop counter.'
    )
)
insert into public.gear_listings (
  title,
  category,
  subcategory,
  description,
  location,
  distance_miles,
  price_per_day,
  deposit_amount,
  replacement_value,
  rating,
  review_count,
  owner_name,
  owner_type,
  availability_status,
  condition,
  image_url,
  features,
  safety_notes,
  pickup_instructions,
  listing_status
)
select
  title,
  category,
  subcategory,
  description,
  location,
  distance_miles,
  price_per_day,
  deposit_amount,
  replacement_value,
  rating,
  review_count,
  owner_name,
  owner_type,
  availability_status,
  condition,
  image_url,
  features,
  safety_notes,
  pickup_instructions,
  'active'
from seed_listings
where not exists (
  select 1
  from public.gear_listings existing
  where existing.title = seed_listings.title
    and existing.owner_name = seed_listings.owner_name
);
